name: .NET Core with web deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # build .net core web app
  buildWeb:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish --no-restore --verbosity normal
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: Web/bin/Debug/netcoreapp3.1/publish
    
    - name: Deploy package to Azure App Service
      uses: Azure/webapps-deploy@v2.1
      with:
        # Name of the Azure Web App
        app-name: stephgouMercuryHealth
        # Applies to Web Apps(Windows and Linux) and Web App Containers(linux). Multi container scenario not supported. Publish profile (*.publishsettings) file contents with Web Deploy secrets
        publish-profile: ${{ secrets.STEPHGOUMERCURYHEALTHPUBLISHSETTINGS }}
        # Applies to Web App only: Path to package or folder. *.zip, *.war, *.jar or a folder to deploy
        package: Web/bin/Debug/netcoreapp3.1/publish

      
