name: .NET Core

on:
#gollum event to trigger workflow I want to temporary ignore 
#used for runs your workflow when someone creates or updates a Wiki page, which triggers the gollum event.
  gollum
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish --no-restore --verbosity normal
    - name: Echo GITHUB_WORKSPACE
      run: echo ${GITHUB_WORKSPACE}